apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
bases:
- ../../base/
configMapGenerator:
- name: nfs-client-provisioner-env
  behavior: merge
  literals:
  - PROVISIONER_NAME=nfs-storage
  - NFS_SERVER=YOUR_NFS_SERVER
  - NFS_PATH=YOUR_NFS_PATH
patchesJson6902:
- target:
    group: "apps"
    version: v1
    kind: Deployment
    name: nfs-client-provisioner
  path: deployment-volume-patch.yaml
